[workspace]
channels = ["conda-forge"]
name = "gpt2-from-scratch"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
ipykernel = ">=6.30.1,<7"
transformers = ">=4.55.2,<5"
pytorch = ">=2.8.0,<3"
matplotlib = ">=3.10.5,<4"
tiktoken = ">=0.9.0,<0.10"
